create database nykaa_marketcampperf;
use nykaa_marketcampperf;

select * from nykaa_campaign_data;

desc nykaa_campaign_data;

SET SQL_SAFE_UPDATES = 0;

alter table nykaa_campaign_data
add new_date date;

-- str_to_date is used to convert date from any format to SQL date format 
-- In case the format is sql format and data type is text we can do that by alter....modify....
update nykaa_campaign_data
set new_date = str_to_date(`date`, "%d-%m-%Y");

alter table nykaa_campaign_data
drop column `date`;

-- Q1. Find the total revenue generated by each marketing channel.
select channel_used, sum(revenue) as Total_revenue
from nykaa_campaign_data
group by channel_used
order by total_revenue desc;
-- Not splitting the values which are in combined form as it is showing the combined performance of the platforms. 

-- Q2. Find total conversions for each campaign type.
select campaign_type, sum(conversions) as total_conversions
from nykaa_campaign_data
group by campaign_type
order by total_conversions desc;

-- Q3. Which audience type generated the highest revenue.
select target_audience, sum(revenue) as total_revenue
from nykaa_campaign_data
group by target_audience
order by total_revenue desc;

-- Q4. Find campaigns where clicks are greater than 10000.
select campaign_id, sum(clicks) as total_clicks
from nykaa_campaign_data
group by campaign_id
having total_clicks > 10000;
-- or
select campaign_id, clicks
from nykaa_campaign_data
where clicks > 10000;

-- Q5. Find averege campaigns duration by channel
select channel_used, avg(duration)
from nykaa_campaign_data
group by channel_used
order by avg(duration) desc;

-- KPI based Questions
-- Q6. Calculate CTR for each campaigns. CTR = (Total clicks / Total Imperssions) * 100
select campaign_id, (sum(clicks) / sum(impressions)) * 100 as CTR
from nykaa_campaign_data
group by campaign_id;

-- Q7. Find top 5 campaigns with highest conversions rate. Conversion Rate = conversions / clicks * 100
select campaign_id, round(conversions / clicks * 100, 2) as conversion_rate
from nykaa_campaign_data
where clicks > 0
order by conversion_rate desc limit 5;

-- How would you calculate CPA if spend data is available: 
-- Concept > Cost per Aquistion (CPA) = spend / conversions

-- ROI = (Revenue - Spend) / Spend * 100
-- Explain how ROI Dashbaord was created
-- I first calculated revenue generated form each campaign and compared it against marketing spend.
-- Then I created KPIs like ROI%, CTR, Conversion Rate, CPA using cards, bar charts, trend visuals for
-- campaign performance comparisson across paltform.

-- Q9. Find the most profitable campaign type
select campaign_type, sum(revenue) 
from nykaa_campaign_data
group by campaign_type
order by sum(revenue) desc limit 1;

-- Q10. Which channel genrated max leads but low conversions
-- we have used concept of conversion effeciency here, CE = conversions / leads * 100
SELECT channel_used,
       SUM(leads) AS total_leads,
       SUM(conversions) AS total_conversions,
       ROUND(SUM(conversions) * 100.0 / SUM(leads),2) AS conversion_efficiency
FROM nykaa_campaign_data
GROUP BY channel_used
ORDER BY total_leads DESC,
         conversion_efficiency ASC;
         
-- Q11. Find the campaigns where conversion are below average
select campaign_id from nykaa_campaign_data
where conversions < ( select avg(conversions) from nykaa_campaign_data);

-- Q12. Find the campaigns where conversion rate is below average
with conv_rate_calc as(
select campaign_id, round(sum(conversions) / sum(clicks) * 100, 2) as conv_rate
from nykaa_campaign_data
where clicks > 0
group by campaign_id )
select campaign_id, conv_rate from conv_rate_calc
where conv_rate < (select avg(conv_rate) from conv_rate_calc);

-- Q12. Find top-performing platform based on revenue per click
with rev_clk_calc as (
select channel_used, round(sum(revenue) / sum(clicks), 2) as rev_per_clk
from nykaa_campaign_data
group by channel_used)
select channel_used 
from rev_clk_calc 
order by rev_per_clk desc limit 5;

-- Q13. Rank campaigns based on revenue within each platform
select campaign_id, revenue, channel_used,
rank() over(partition by channel_used order by revenue desc) as camp_perf
from nykaa_campaign_data;

-- Q14. Find cumulative revenue generated over campaigns
select campaign_id, new_date, revenue,                          
sum(revenue) over (order by campaign_id) as cum_revenue    -- haven't use date in order by coz dates can be same
from nykaa_campaign_data;

-- Q15. Find pervious campaign revenue and display them with present time revenue
select campaign_id, revenue, new_date,
lag (revenue) over (order by campaign_id asc) as prev_rev 
from nykaa_campaign_data;
-- I used lag to compare current campaign performance with previous campaign perfromance to identify revenue drops & sudden spikes

-- Q16. Identify underperforming campaigns i.e., High Impressions, Low Clicks, Low Conversions
select campaign_id, impressions, clicks, conversions
from nykaa_campaign_data
where impressions > 10000 and clicks < 5000 and conversions < 500;

-- Q17. Which target audience respond better to influencer campaigns
select campaign_type, target_audience, sum(conversions) as conversions
from nykaa_campaign_data
where campaign_type = "Influencer"
group by target_audience
order by conversions desc;

select * from nykaa_campaign_data;

-- Q18. Find campaign efficiency accross channels
select channel_used, round(sum(conversions) / sum(clicks) * 100, 2) rate_of_conversions
from nykaa_campaign_data
group by channel_used
order by rate_of_conversions desc;

-- Q19. Find campaigns contributing 80% of the total revenue
with revenue_cte as (
select campaign_id, revenue,
sum(revenue) over (order by revenue desc) as recurring_revenue,
sum(revenue) over () as total_revenue
from nykaa_campaign_data)
select campaign_id, revenue
from revenue_cte
where recurring_revenue <= total_revenue * 0.80;

-- Q20. Detect campaigns with abnormat click through behaviour
select campaign_id, clicks, impressions,
round(clicks / impressions * 100, 2) as ctr 
from nykaa_campaign_data
where (clicks / impressions * 100) > 50;

-- Q21. Find Top 3 campaigns from each platform
with rank_cte as
(select campaign_id, revenue, channel_used,
dense_rank () over (partition by channel_used order by revenue desc) as  top_perf
from nykaa_campaign_data)
select campaign_id, revenue, channel_used, top_perf
from rank_cte
where top_perf <= 3;

-- Q22. Find month over month revenue growth
-- Growth rate = current month revenue - previous month revenue / previous month revenue * 100
with revenue_cte as (
select month(new_date) as month_num, sum(revenue) as current_mnth_rev, monthname(new_date) as mnth_name
from nykaa_campaign_data
group by month(new_date), monthname(new_date)
order by month(new_date))
select  month_num, current_mnth_rev, mnth_name,
lag(current_mnth_rev) over (order by month_num) as prev_mnth_rev,
round((current_mnth_rev - lag(current_mnth_rev) over (order by month_num)) / lag(current_mnth_rev) over (order by month_num) * 100, 2) as mnth_grth_rate
from revenue_cte;

-- Q23. How would you identify duplicate campaigns
select campaign_id, count(*)
from nykaa_campaign_data
group by campaign_id 
having count(*) > 1;

-- Q24. Find campaigns where clicks exceeds impressions
-- this is to check the data integrity issues because clicks can't be higher then impressions
select campaign_id 
from nykaa_campaign_data
where clicks > impressions;

-- Q25. Build a customer funnel analysis using SQL
select sum(impressions) as total_impressions,
sum(clicks) as total_clicks,
sum(leads) as total_leads,
sum(conversions) as total_conversions
from nykaa_campaign_data;



